_target_: ctd.task_modeling.task_env.multi_task_env.MultiTaskWrapper
dataset_name: MultiTaskInt
task_list:
  - DelayPro
  - MemoryPro
  - ReactPro
  - DelayAnti
  - MemoryAnti
  - ReactAnti
  - IntMod1
  - IntMod2
  - ContextIntMod1
  - ContextIntMod2
  - ContextIntMultimodal
  - Match2Sample
  - NonMatch2Sample
  - MatchCatPro
  - MatchCatAnti

n_timesteps: 640
noise: 0.3
dynamic_noise: 0.0
num_targets: 32
bin_size: 20
grouped_sampler: True
latent_l2_wt: 0.0
