_target_: ctd.task_modeling.task_env.multi_task_env.MultiTaskWrapper
dataset_name: MultiTaskMemory
task_list:
  - MemoryPro
  - MemoryAnti

n_timesteps: 450
dynamic_noise: 0.0
noise: 0.3
num_targets: 32
bin_size: 20
grouped_sampler: True
latent_l2_wt: 1.0e-6
