batch_size: 1000
data_env: !!python/object:ctd.task_modeling.task_env.task_env.NBitFlipFlop
  action_space: !!python/object:gymnasium.spaces.box.Box
    _np_random: null
    _shape: !!python/tuple
    - 3
    bounded_above: !!python/object/apply:numpy._core.multiarray._reconstruct
      args:
      - &id001 !!python/name:numpy.ndarray ''
      - !!python/tuple
        - 0
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple
        - 3
      - &id002 !!python/object/apply:numpy.dtype
        args:
        - b1
        - false
        - true
        state: !!python/tuple
        - 3
        - '|'
        - null
        - null
        - null
        - -1
        - -1
        - 0
      - false
      - !!binary |
        AQEB
    bounded_below: !!python/object/apply:numpy._core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple
        - 0
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple
        - 3
      - *id002
      - false
      - !!binary |
        AQEB
    dtype: &id004 !!python/object/apply:numpy.dtype
      args:
      - f4
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    high: !!python/object/apply:numpy._core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple
        - 0
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple
        - 3
      - &id003 !!python/object/apply:numpy.dtype
        args:
        - f4
        - false
        - true
        state: !!python/tuple
        - 3
        - <
        - null
        - null
        - null
        - -1
        - -1
        - 0
      - false
      - !!binary |
        AADAPwAAwD8AAMA/
    high_repr: '1.5'
    low: !!python/object/apply:numpy._core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple
        - 0
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple
        - 3
      - *id003
      - false
      - !!binary |
        AAAAvwAAAL8AAAC/
    low_repr: '-0.5'
  context_inputs: !!python/object:gymnasium.spaces.box.Box
    _np_random: null
    _shape: !!python/tuple
    - 0
    bounded_above: !!python/object/apply:numpy._core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple
        - 0
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple
        - 0
      - *id002
      - false
      - !!binary ""
    bounded_below: !!python/object/apply:numpy._core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple
        - 0
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple
        - 0
      - *id002
      - false
      - !!binary ""
    dtype: *id004
    high: !!python/object/apply:numpy._core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple
        - 0
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple
        - 0
      - *id003
      - false
      - !!binary ""
    high_repr: '[]'
    low: !!python/object/apply:numpy._core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple
        - 0
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple
        - 0
      - *id003
      - false
      - !!binary ""
    low_repr: '[]'
  coupled_env: false
  dataset_name: 3BFF
  dynamic_noise: 0
  input_labels:
  - Input 0
  - Input 1
  - Input 2
  loss_func: !!python/object:ctd.task_modeling.task_env.loss_func.NBFFLoss
    transition_blind: 4
  n: 3
  n_timesteps: 500
  noise: 0.15
  observation_space: !!python/object:gymnasium.spaces.box.Box
    _np_random: null
    _shape: !!python/tuple
    - 3
    bounded_above: !!python/object/apply:numpy._core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple
        - 0
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple
        - 3
      - *id002
      - false
      - !!binary |
        AQEB
    bounded_below: !!python/object/apply:numpy._core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple
        - 0
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple
        - 3
      - *id002
      - false
      - !!binary |
        AQEB
    dtype: *id004
    high: !!python/object/apply:numpy._core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple
        - 0
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple
        - 3
      - *id003
      - false
      - !!binary |
        AADAPwAAwD8AAMA/
    high_repr: '1.5'
    low: !!python/object/apply:numpy._core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple
        - 0
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple
        - 3
      - *id003
      - false
      - !!binary |
        AADAvwAAwL8AAMC/
    low_repr: '-1.5'
  output_labels:
  - Output 0
  - Output 1
  - Output 2
  state: !!python/object/apply:numpy._core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 3
    - !!python/object/apply:numpy.dtype
      args:
      - f8
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - false
    - !!binary |
      AAAAAAAAAAAAAAAAAADwPwAAAAAAAAAA
  switch_prob: 0.015
  transition_blind: 4
input_size: null
learning_rate: 0.001
model: null
n_samples: 1000
num_workers: 4
output_size: null
seed: 0
task_env: null
weight_decay: 1.0e-10
